### ISSUE TITLE
Ability to #include a file with all lines indented

### ISSUE THREAD

**Issue by computator** [logological/gpp#68]
I would like to be able to include one file inside another, but have the contents of the included file all indented by a certain amount. For example:

**`test.inc`**
```
multiline
example
```
**`test.yaml`**
```yaml
example:
  content: |
    #include_indented test.inc
  other: asdf
```
Intended result:
```yaml
example:
  content: |
    multiline
    example
  other: asdf
```

I am not sure if this is currently possible with gpp only? If so, I couldn't figure out how. Perhaps there's a way to use the output of include in a macro to then prefix all the lines with a string?

The only solution I could come up with so far is using exec, which I would prefer to avoid if possible.
